In [2]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [3]:
a = np.random.rand(3,4)
print(a)
a[[0, 2]] = a[[2, 0]]
print(a)

[[0.10219188 0.23031626 0.95202663 0.49298697]
 [0.42526613 0.24224959 0.91734068 0.51667002]
 [0.42496694 0.80620643 0.73060232 0.15509861]]
[[0.42496694 0.80620643 0.73060232 0.15509861]
 [0.42526613 0.24224959 0.91734068 0.51667002]
 [0.10219188 0.23031626 0.95202663 0.49298697]]


**75. How to compute averages using a sliding window over an array?**

In [7]:
def moving_average ( a , n):
    test = np.cumsum(a, dtype =float)
    test[n:] = test[n:]- test[:-n]
    return test[n - 1:] /n
array = np.arange(30)
print(array)
moving_average(array,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28.])