In [4]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [13]:
arr = np.random.rand(10,10)
print(arr)
print(np.amin(arr))
print(np.amax(arr))

[[0.03801763 0.0752403  0.11251897 0.07557966 0.00250393 0.67483812
  0.23552649 0.02176597 0.72386313 0.9195707 ]
 [0.15927756 0.3460394  0.9755892  0.94056638 0.61045217 0.35618768
  0.83476457 0.22434614 0.28383036 0.02543006]
 [0.55583377 0.05599562 0.26024024 0.01907153 0.83958637 0.72202114
  0.83387728 0.31517457 0.57431122 0.91709747]
 [0.27447348 0.72652829 0.54597682 0.57460902 0.5487079  0.3053193
  0.76902822 0.5824001  0.55892507 0.98599127]
 [0.12250167 0.76581409 0.21325402 0.10436379 0.60663361 0.0039758
  0.658754   0.02841898 0.95551917 0.3708689 ]
 [0.99812302 0.5171022  0.46810356 0.89214665 0.39208103 0.11189868
  0.25257238 0.38666396 0.17604209 0.60251857]
 [0.69253511 0.0835106  0.38020678 0.66873914 0.64149671 0.67446619
  0.27673999 0.56946344 0.82739869 0.0505667 ]
 [0.78856259 0.21531228 0.34638773 0.31996683 0.03593214 0.48074037
  0.31675394 0.20556631 0.00455406 0.08102899]
 [0.59098278 0.70024181 0.5665496  0.66363083 0.27340747 0.75332975
  0.40715015 0

**15. Create a 2d array with 1 on the border and 0 inside**

In [20]:
ddarr = np.ones((10,10))
print(ddarr)
ddarr[1:-1,1:-1] = 0
print(ddarr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
